os: linux
sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 3.4
          if: branch != master
        - python: 3.5
          if: branch != master
        - python: 3.6
branches:
  only:
  - master
  - develop
install:
  - pip install --upgrade pip
  - pip install -r artifactory_du/requirements.txt
script:
  - printenv
  - ls -la
  - python -m pytest tests

deploy:
- provider: pypi
  user: devopshq
  password:
    secure: "OEUMpcA+R4jj59lhw99hSz9RI0FbQF2Oz1tr77Shxf8FNUflsLqjQIIdtUfUEwsxt3paEYJQmc6TMciRZTpaup+iADdeCBYAEl3E42xKs5i+q4765BTO8G6fQQP1mIDakty2pBX97YzinjARrcDw+hB5XkcRY2qWKjbpnutBWtYT9WYmBsLABq4pM35rwhrj0Bh7mKu56XrxjemIb5zDZFmC1kZW/5yhYx3L+YoN88dkypcAsmcVaEZC9es5D20wqeVTQYGfkKbgw4mVxQENlJ7DeM8fS/3gTWBTemn1HDEA02K+C6vVEUiFuXHIV60B47O/mZmt64o7bdXhPtlAS0VUjqDkid4k/3GPjMXqoNbMR2rSt5PhuwIGxskNFTv+nvvEKiJE/3eqS6g9Dx5r5Ix8elCgPnUTvxvRzXv2tCto5/8qA+tWo3aPyYciCSAXN1I9h333zIaxZVNac+37KUS/Go+sYSqbnj53kTojvtKvVnLV/FrE4vy5rh7tC4ctgxRcjYIDSiSsCEHMHV4Vd4QQPXpJWGFMnwss3zTYZbTtlAsAtFnBhhnDL7EjkTkrcTDBD/kJrX2yTTuOGguXeeHRLTLTk09s75yVHkPbmp73ul+JNw7WFeldVBu8NmSxZuuJAD3AFERlsf2t9tDU1wwnHjyguWz2i7EZ7ajC7K4="
  distributions: sdist bdist_wheel
  on:
    branch: master
  skip_cleanup: true
